objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Image__c</fullName>
        <inlineHelpText>Post an image (200px wide, transparent .PNG recommended) in the &quot;Product Images&quot; folder of Documents.  Copy the Record ID (in the URL) of the new document and paste it here.</inlineHelpText>
        <label>Image ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

clientelling/objects/Recommended_Product__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recommended Products</relationshipLabel>
        <relationshipName>Recommended_Products1ab</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <formula>IMAGE( Product__r.Small_Img_URL__c , &quot;Image&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Recommended Products</relationshipLabel>
        <relationshipName>Recommended_Productsab</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recommended Product</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Recommended Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AB_cartierRecommendedCtrl.cls
public class AB_cartierRecommendedCtrl {
    
    @AuraEnabled
    public static List<Recommended_Product__c> recommendedList(String clickedContact){
        List<Recommended_Product__c> recProds = [SELECT Contact__c,Id,Image__c,Name,Product__c,Product__r.Name,Product__r.Image__c FROM Recommended_Product__c WHERE Contact__c =:clickedContact];
        
        System.debug('recProds: '+recProds);
        return recProds;
        
    }
    
    
    
}