objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Image__c</fullName>
        <inlineHelpText>Post an image (200px wide, transparent .PNG recommended) in the &quot;Product Images&quot; folder of Documents.  Copy the Record ID (in the URL) of the new document and paste it here.</inlineHelpText>
        <label>Image ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

clientelling/objects/Purchases__c.object
<CustomObject>
    <description>Retail IDO Custom Object</description>
    <fields>
        <fullName>Customer__c</fullName>
        <description>Retail IDO Custom Field</description>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Item_Interestsab</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <description>Retail IDO Custom Field</description>
        <formula>IMAGE(&apos;/resource/1383764845000/sap_logo&apos;,&quot;SAP&quot;,20,40)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>From</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Small__c</fullName>
        <formula>IMAGE(Product__r.Small_Img_URL__c , &quot;Image&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <formula>IMAGE( Product__r.Image_URL__c  , &quot;No Image&quot;, 180, 120)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Purchases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase History</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Purchase ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AB_cartierHistoryListCtrl.cls
public class AB_cartierHistoryListCtrl {
   
    @AuraEnabled
    public static List<Purchases__c> purchaseList(String clickedContact){
        List<Purchases__c> purchList = [SELECT Customer__c,From__c,Id,Image_Small__c,Image__c,Name,Product__c,Product__r.Name,Product__r.Image__c FROM Purchases__c WHERE Customer__c =:clickedContact];
        
        System.debug('Purchases: '+purchList);
        System.debug('Clicked Contact: '+clickedContact);
        
        return purchList;
        
        
    }
}