clientelling/objects/Appointment__c.object
<CustomObject>
    <description>Used by LiveMessage texting to set, change and cancel appointments.</description>
    <fields>
        <fullName>Appointment_Time__c</fullName>
        <label>Appointment Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointmentsab</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Checked In</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Clienteling_App_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Logo_Height__c</fullName>
        <inlineHelpText>The height of the logo in px</inlineHelpText>
        <label>Logo Height</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Logo_Resource_Name__c</fullName>
        <inlineHelpText>This is the name of the static resource you have uploaded for the app logo.</inlineHelpText>
        <label>Logo Resource Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo_Width__c</fullName>
        <inlineHelpText>The width of the logo in px</inlineHelpText>
        <label>Logo Width</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Performance_Dashboard_Id__c</fullName>
        <inlineHelpText>The unique ID of the wave dashboard. You can get a dashboard’s ID, an 18-character code beginning with 0FK, from the dashboard&apos;s URL.</inlineHelpText>
        <label>Performance Dashboard Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Clienteling App Configuration</label>
    <nameField>
        <label>Clienteling App Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clienteling App Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clientelling/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Bronze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/AB_cartierAssignmentsCtrl.cls
public class AB_cartierAssignmentsCtrl {
    @auraEnabled
    public static List<Task> myAssignmentList(){
        
        List<Task> assignments = [SELECT ActivityDate,Who.Name,Contact_Pic_URL__c,OwnerId,Id,Status,Subject,WhoId FROM Task WHERE Status != 'Completed' AND ActivityDate != NULL AND WhoId != NULL AND OwnerId=:UserInfo.getUserId() ORDER BY ActivityDate DESC LIMIT 25];
        return assignments;
        
        }
        
        @auraEnabled
        public static List<Appointment__c> myAppointments(){
            List<Appointment__c> apps = [SELECT Appointment_Time__c,Contact__c,Id,Name,Contact__r.Name,Status__c,CreatedDate FROM Appointment__c WHERE Status__c != 'Completed' ORDER BY CreatedDate DESC LIMIT 8];
            return apps;
        }
        
        @auraEnabled
        public static List<Contact> listContacts(){
            
            List<Contact> listC = [SELECT Birthdate,Email,Id,Title,OwnerId,Name,Phone,Account.Name FROM Contact WHERE OwnerId=:UserInfo.getUserId() ORDER BY CreatedDate DESC LIMIT 12];
            return listC;
            
        }
        
        @auraEnabled
        public static List<Contact> birthdayContacts(){
            
            List <Contact> listB = [SELECT Email,Id,Title,Name,Phone,Account.Name,Birthdate FROM Contact WHERE Birthdate = TODAY];
            return listB;
            
        }
    
    @auraEnabled
    public static List<Event> listEvents(){
        
        List <Event> listE = [SELECT AccountId,ActivityDate,Description,Id,Type,Location,Subject,WhatId,WhoId,Who.Name FROM Event ORDER BY ActivityDate DESC LIMIT 12];
        return listE;
        
    }
        
        @auraEnabled
        public static User getUserinfoTwo(){
            User cUser = [SELECT AccountId,FirstName,Id,Email,City,Country,Title,LastName,SmallPhotoUrl,MediumPhotoUrl,MobilePhone,Name,Phone FROM User WHERE id=:UserInfo.getUserId()];
            System.debug('cUser: ' + cUser);
            return cUser;
        }  
    
    @auraEnabled
    public static Clienteling_App_Configuration__c clientConfigTwo(){
        
        Clienteling_App_Configuration__c conTwo = [SELECT Active__c,Id,Logo_Height__c,Logo_Resource_Name__c,Logo_Width__c,Name,Performance_Dashboard_Id__c FROM Clienteling_App_Configuration__c WHERE Active__c = TRUE LIMIT 1];
        
        return conTwo;
        
        
    }
    }