clientelling/objects/Appointment__c.object
<CustomObject>
    <description>Used by LiveMessage texting to set, change and cancel appointments.</description>
    <fields>
        <fullName>Appointment_Time__c</fullName>
        <label>Appointment Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shopping</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Fitting</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clientelling/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Retail Custom FIeld</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                    <isActive>false</isActive>
                    <label>F</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <isActive>false</isActive>
                    <label>M</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <description>Retail Custom Field</description>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single</fullName>
                </value>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>Divorced</fullName>
                </value>
                <value>
                    <fullName>Widow</fullName>
                </value>
                <value>
                    <fullName>Widower</fullName>
                </value>
                <value>
                    <fullName>Domestic Partnership</fullName>
                </value>
                <value>
                    <fullName>Never married</fullName>
                    <isActive>false</isActive>
                    <label>Never married</label>
                </value>
                <value>
                    <fullName>Separated</fullName>
                    <isActive>false</isActive>
                    <label>Separated</label>
                </value>
                <value>
                    <fullName>Widowed</fullName>
                    <isActive>false</isActive>
                    <label>Widowed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

clientelling/classes/AB_carterStoreVisitCtrl.cls
public class AB_carterStoreVisitCtrl {
    
    @auraEnabled
    public static Appointment__c createVisit(String descriptionBox, String reasonSelect, Datetime startDate, Datetime endDate){
        
        Appointment__c visit = new Appointment__c();
        
        visit.Name = descriptionBox;
        visit.Appointment_Time__c = startDate;
        visit.Reason__c = reasonSelect;
        
        
        insert visit;
        return visit;
    }
    
    @auraEnabled
    public static Contact createCon(String fNameC, String lNameC, String selectGender, String selectMarital, 
                                    String email, String mobilePhone, Date birthDate){
                                        
                                        Contact c = new Contact();
                                        
                                        c.FirstName = fnameC;
                                        c.LastName = lNameC;
                                        c.Gender__c = selectGender;
                                        c.Marital_Status__c = selectMarital;
                                        c.Email = email;
                                        c.Phone = mobilePhone;
                                        c.Birthdate = birthDate;
                                        
                                        insert c;
                                        return c;
                                    }
    
    @auraEnabled
    public static User getUser(){
        User tUser = [SELECT AccountId,FirstName,Id,Email,Title,LastName,MobilePhone,Name,Phone FROM User WHERE id=:UserInfo.getUserId()];
        System.debug('the user is: ' + tUser);
        return tUser;
    }  

    
}