clientelling/objects/Contact.object
<CustomObject>
   <fields>
        <fullName>Cust360_Contact_Picture_URL__c</fullName>
        <label>Contact Picture URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Retail Custom FIeld</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                    <isActive>false</isActive>
                    <label>F</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <isActive>false</isActive>
                    <label>M</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Management</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Sales/Office</fullName>
                </value>
                <value>
                    <fullName>Farming/Fishing</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Production/Transport</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Bronze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/AB_cartierContactRecordCtrl.cls
public class AB_cartierContactRecordCtrl {
    
    @auraEnabled
    public static Contact getContactInfo(String clickedContact){
        System.debug('clicked contact: ' + clickedContact);
        
        Contact con = [SELECT Birthdate,Gender__c,Title,Description,Status__c,Email,FirstName,Id,LastName,LeadSource,Cust360_Contact_Picture_URL__c,Name,Phone FROM Contact WHERE Id=: clickedContact];
        
        System.debug('con: ' + con);
        return con;
    }  
    
    @auraEnabled
    public static Contact updateContact(String description, String fName, String lName, String genderEdit, String Phone, String Email, Date Birthdate, String Occupation, String LeadSource, Id clickedContact){
        
        Contact c = [SELECT Birthdate,Gender__c,Description,Title,Status__c,Email,FirstName,Id,LastName,Name,Phone FROM Contact WHERE Id=:clickedContact];
        
        c.FirstName = fName;
        c.LastName = lName;
        c.Description = description;
        c.Gender__c = genderEdit;
        c.Phone = Phone;
        c.Email = Email;
        c.LeadSource = LeadSource;
        c.Birthdate = Birthdate;
        c.Occupation__c = Occupation;
        
        update c;
        return c;
    }
    
    
}